# Generated by Django 5.2.5 on 2025-08-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicProductLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('token', models.CharField(default='befc7e06cb9c4314be006e4bd7e5d850', max_length=32, unique=True)),
                ('product_data', models.JSONField()),
            ],
        ),
    ]
