# Generated by Django 5.2.5 on 2025-08-19 16:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicproductlink',
            name='product_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publicproductlink',
            name='product_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='publicproductlink',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
